import { ColorModeScript } from '@chakra-ui/color-mode'
import Document, { Html, Head, Main, NextScript } from 'next/document'
import { theme } from './_app'

class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const initialProps = await Document.getInitialProps(ctx)
		return { ...initialProps }
	}

	render() {
		return (
			<Html>
				<Head>
					<meta name='description' content='Generated by create next app' />
					<link rel='preconnect' href='https://fonts.googleapis.com' />
					<link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='true' />
					<link
						href='https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap'
						rel='stylesheet'
					/>
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<body>
					<ColorModeScript initialColorMode={theme.config.initialColorMode} />
					<Main />
					<NextScript />
				</body>
			</Html>
		)
	}
}

export default MyDocument
